algoritmo "semnome"
// Função :
// Autor :
// Data : 10/03/2021
// Seção de Declarações
var

nome, sexo : caractere

inicio

escreval ("Qual o seu nome?")
leia (nome)

escreval ("Qual o seu sexo, M ou F?")
leia (sexo)

escolha sexo

caso "M"
   escreval (nome," é Homem")

caso "F"
   escreval (nome, " é Mulher")

outrocaso
   escreval ("Inválido")

fimescolha




fimalgoritmo
