algoritmo "semnome"
// Função :
// Autor :
// Data : 01/06/2021
// Seção de Declarações
var

num1, num2 : real
Sua_opcao, parar : caractere

Procedimento Proc_somar
inicio
escreval("Informe o primeiro número:")
leia(num1)
escreval("Infoprme o segundo número:")
leia(num2)

escreval("Resultado= ",num1 + num2:6:2)

Fimprocedimento


inicio
// Seção de Comandos

Proc_somar

fimalgoritmo
