algoritmo "semnome"
// Função :
// Autor :
// Data : 09/03/2021
// Seção de Declarações
var

a, b : real

inicio
// Seção de Comandos

escreval ("Informe o valor de A:")
leia (a)

escreval ("Informe o valor de B")
leia (b)

se (a = b) entao
   escreval ("A e B são iguais")
fimse

se (a > B) entao
   escreval ("O maior é o número A")

senao
   escreval ("O maior é o número B")

fimse



fimalgoritmo
